#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar & hypridle & swaync & swayosd-server && wl-gammarelay-rs
exec-once = hyprpaper
exec-once = hyprctl dispatch workspace 1
exec-once = rofi-polkit-agent -theme ~/.config/rofi/scripts/rofi-polkit-agent.rasi
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = cliphist wipe
