###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
# $fileManager = dolphin
$fileManager = nautilus
$menu = rofi -show drun #wofi --show drun #  "rofi -show drun" 
$ROFI = $HOME/.config/rofi/scripts/rofi.sh
$browser = google-chrome-stable
$editor = code
$notion = notion-app